//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Microsoft.Web.Services3;
using Microsoft.Web.Services3.Design;
using Microsoft.Web.Services3.Security.Tokens;

namespace IntegraAfirmaNet.TSA
{
// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="CreateTimeStampBinding", Namespace="http://www.map.es/TSA/V1/TSA.wsdl")]
    [XmlInclude(typeof(DocumentBaseType))]
    [XmlInclude(typeof(RequestBaseType))]
    public partial class CreateTimeStampBinding : WebServicesClientProtocol
    {
    
        private System.Threading.SendOrPostCallback createTimeStampOperationCompleted;
    
        /// <remarks/>
        public CreateTimeStampBinding() {
            this.Url = "http://des-tsafirma.redsara.es:80/tsamap/CreateTimeStampWS";
        }
    
        /// <remarks/>
        public event createTimeStampCompletedEventHandler createTimeStampCompleted;
    
        /// <remarks/>
        [SoapDocumentMethod("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: XmlElement("SignResponse", Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
        public SignResponse createTimeStamp([XmlElement(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")] SignRequest SignRequest) {
            object[] results = this.Invoke("createTimeStamp", new object[] {
                SignRequest});
            return ((SignResponse)(results[0]));
        }

        /// <remarks/>
        [SoapDocumentMethod("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: XmlElement("SignResponse", Namespace = "urn:oasis:names:tc:dss:1.0:core:schema")]
        public SignResponse createTimeStampCertificado(String keystorePath, String keystorePassword, [XmlElement(Namespace = "urn:oasis:names:tc:dss:1.0:core:schema")] SignRequest SignRequest)
        {
            if (string.IsNullOrWhiteSpace(keystorePath))
            {
                throw new ArgumentNullException("keystorePath", "Falta la ruta del certificado");
            }

            Tools.ExternalX509TokenProvider tokenProvider = new Tools.ExternalX509TokenProvider(keystorePath, keystorePassword);
            X509SecurityToken token = tokenProvider.GetToken();

            AfirmaPolicyAssertions.X509SecurityTokenSoapAssertion assertion = new AfirmaPolicyAssertions.X509SecurityTokenSoapAssertion(token);

            Policy policy = new Policy();
            policy.Assertions.Add(assertion);

            this.SetPolicy(policy);

            //XmlDocument doc = new XmlDocument();
            //doc.LoadXml(peticion);

            object[] results = this.Invoke("createTimeStamp", new object[] {
                SignRequest});
            return ((SignResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegincreateTimeStamp(SignRequest SignRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createTimeStamp", new object[] {
                SignRequest}, callback, asyncState);
        }
    
        /// <remarks/>
        public SignResponse EndcreateTimeStamp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SignResponse)(results[0]));
        }
    
        /// <remarks/>
        public void createTimeStampAsync(SignRequest SignRequest) {
            this.createTimeStampAsync(SignRequest, null);
        }
    
        /// <remarks/>
        public void createTimeStampAsync(SignRequest SignRequest, object userState) {
            if ((this.createTimeStampOperationCompleted == null)) {
                this.createTimeStampOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateTimeStampOperationCompleted);
            }
            this.InvokeAsync("createTimeStamp", new object[] {
                SignRequest}, this.createTimeStampOperationCompleted, userState);
        }
    
        private void OncreateTimeStampOperationCompleted(object arg) {
            if ((this.createTimeStampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createTimeStampCompleted(this, new createTimeStampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="VerifyTimeStampBinding", Namespace="http://www.map.es/TSA/V1/TSA.wsdl")]
    [XmlInclude(typeof(DocumentBaseType))]
    [XmlInclude(typeof(RequestBaseType))]
    public partial class VerifyTimeStampBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
        private System.Threading.SendOrPostCallback verifyTimeStampOperationCompleted;
    
        /// <remarks/>
        public VerifyTimeStampBinding() {
            this.Url = "http://des-tsafirma.redsara.es:80/tsamap/VerifyTimeStampWS";
        }
    
        /// <remarks/>
        public event verifyTimeStampCompletedEventHandler verifyTimeStampCompleted;
    
        /// <remarks/>
        [SoapDocumentMethod("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: XmlElement("VerifyResponse", Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
        public ResponseBaseType verifyTimeStamp([XmlElement(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")] VerifyRequest VerifyRequest) {
            object[] results = this.Invoke("verifyTimeStamp", new object[] {
                VerifyRequest});
            return ((ResponseBaseType)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginverifyTimeStamp(VerifyRequest VerifyRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("verifyTimeStamp", new object[] {
                VerifyRequest}, callback, asyncState);
        }
    
        /// <remarks/>
        public ResponseBaseType EndverifyTimeStamp(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResponseBaseType)(results[0]));
        }
    
        /// <remarks/>
        public void verifyTimeStampAsync(VerifyRequest VerifyRequest) {
            this.verifyTimeStampAsync(VerifyRequest, null);
        }
    
        /// <remarks/>
        public void verifyTimeStampAsync(VerifyRequest VerifyRequest, object userState) {
            if ((this.verifyTimeStampOperationCompleted == null)) {
                this.verifyTimeStampOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverifyTimeStampOperationCompleted);
            }
            this.InvokeAsync("verifyTimeStamp", new object[] {
                VerifyRequest}, this.verifyTimeStampOperationCompleted, userState);
        }
    
        private void OnverifyTimeStampOperationCompleted(object arg) {
            if ((this.verifyTimeStampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verifyTimeStampCompleted(this, new verifyTimeStampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="RenewTimeStampBinding", Namespace="http://www.map.es/TSA/V1/TSA.wsdl")]
    [XmlInclude(typeof(DocumentBaseType))]
    [XmlInclude(typeof(RequestBaseType))]
    public partial class RenewTimeStampBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
        private System.Threading.SendOrPostCallback renewTimeStampOperationCompleted;
    
        /// <remarks/>
        public RenewTimeStampBinding() {
            this.Url = "http://des-tsafirma.redsara.es:80/tsamap/RenewTimeStampWS";
        }
    
        /// <remarks/>
        public event renewTimeStampCompletedEventHandler renewTimeStampCompleted;
    
        /// <remarks/>
        [SoapDocumentMethod("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void renewTimeStamp([XmlElement(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")] ref SignRequest SignRequest) {
            object[] results = this.Invoke("renewTimeStamp", new object[] {
                SignRequest});
            SignRequest = ((SignRequest)(results[0]));
        }
    
        /// <remarks/>
        public System.IAsyncResult BeginrenewTimeStamp(SignRequest SignRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("renewTimeStamp", new object[] {
                SignRequest}, callback, asyncState);
        }
    
        /// <remarks/>
        public void EndrenewTimeStamp(System.IAsyncResult asyncResult, out SignRequest SignRequest) {
            object[] results = this.EndInvoke(asyncResult);
            SignRequest = ((SignRequest)(results[0]));
        }
    
        /// <remarks/>
        public void renewTimeStampAsync(SignRequest SignRequest) {
            this.renewTimeStampAsync(SignRequest, null);
        }
    
        /// <remarks/>
        public void renewTimeStampAsync(SignRequest SignRequest, object userState) {
            if ((this.renewTimeStampOperationCompleted == null)) {
                this.renewTimeStampOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrenewTimeStampOperationCompleted);
            }
            this.InvokeAsync("renewTimeStamp", new object[] {
                SignRequest}, this.renewTimeStampOperationCompleted, userState);
        }
    
        private void OnrenewTimeStampOperationCompleted(object arg) {
            if ((this.renewTimeStampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.renewTimeStampCompleted(this, new renewTimeStampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class SignRequest : RequestBaseType {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class RequestBaseType {
    
        private AnyType optionalInputsField;
    
        private InputDocuments inputDocumentsField;
    
        private string requestIDField;
    
        private string profileField;
    
        /// <remarks/>
        public AnyType OptionalInputs {
            get {
                return this.optionalInputsField;
            }
            set {
                this.optionalInputsField = value;
            }
        }
    
        /// <remarks/>
        public InputDocuments InputDocuments {
            get {
                return this.inputDocumentsField;
            }
            set {
                this.inputDocumentsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class AnyType {
    
        private System.Xml.XmlElement[] anyField;
    
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ObjectType {
    
        private System.Xml.XmlNode[] anyField;
    
        private string idField;
    
        private string mimeTypeField;
    
        private string encodingField;
    
        /// <remarks/>
        [XmlText()]
        [XmlAnyElement()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SPKIDataType {
    
        private byte[][] sPKISexpField;
    
        private System.Xml.XmlElement anyField;
    
        /// <remarks/>
        [XmlElement("SPKISexp", DataType="base64Binary")]
        public byte[][] SPKISexp {
            get {
                return this.sPKISexpField;
            }
            set {
                this.sPKISexpField = value;
            }
        }
    
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class PGPDataType {
    
        private object[] itemsField;
    
        private ItemsChoiceType1[] itemsElementNameField;
    
        /// <remarks/>
        [XmlAnyElement()]
        [XmlElement("PGPKeyID", typeof(byte[]), DataType="base64Binary")]
        [XmlElement("PGPKeyPacket", typeof(byte[]), DataType="base64Binary")]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
    
        /// <remarks/>
        [XmlEnum("##any:")]
        Item,
    
        /// <remarks/>
        PGPKeyID,
    
        /// <remarks/>
        PGPKeyPacket,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType {
    
        private string x509IssuerNameField;
    
        private string x509SerialNumberField;
    
        /// <remarks/>
        public string X509IssuerName {
            get {
                return this.x509IssuerNameField;
            }
            set {
                this.x509IssuerNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string X509SerialNumber {
            get {
                return this.x509SerialNumberField;
            }
            set {
                this.x509SerialNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType {
    
        private object[] itemsField;
    
        private ItemsChoiceType[] itemsElementNameField;
    
        /// <remarks/>
        [XmlAnyElement()]
        [XmlElement("X509CRL", typeof(byte[]), DataType="base64Binary")]
        [XmlElement("X509Certificate", typeof(byte[]), DataType="base64Binary")]
        [XmlElement("X509IssuerSerial", typeof(X509IssuerSerialType))]
        [XmlElement("X509SKI", typeof(byte[]), DataType="base64Binary")]
        [XmlElement("X509SubjectName", typeof(string))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType {
    
        /// <remarks/>
        [XmlEnum("##any:")]
        Item,
    
        /// <remarks/>
        X509CRL,
    
        /// <remarks/>
        X509Certificate,
    
        /// <remarks/>
        X509IssuerSerial,
    
        /// <remarks/>
        X509SKI,
    
        /// <remarks/>
        X509SubjectName,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RetrievalMethodType {
    
        private TransformType[] transformsField;
    
        private string uRIField;
    
        private string typeField;
    
        /// <remarks/>
        [XmlArrayItem("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType {
    
        private object[] itemsField;
    
        private string[] textField;
    
        private string algorithmField;
    
        /// <remarks/>
        [XmlAnyElement()]
        [XmlElement("XPath", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RSAKeyValueType {
    
        private byte[] modulusField;
    
        private byte[] exponentField;
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] Modulus {
            get {
                return this.modulusField;
            }
            set {
                this.modulusField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] Exponent {
            get {
                return this.exponentField;
            }
            set {
                this.exponentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DSAKeyValueType {
    
        private byte[] pField;
    
        private byte[] qField;
    
        private byte[] gField;
    
        private byte[] yField;
    
        private byte[] jField;
    
        private byte[] seedField;
    
        private byte[] pgenCounterField;
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] Seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] PgenCounter {
            get {
                return this.pgenCounterField;
            }
            set {
                this.pgenCounterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyValueType {
    
        private object itemField;
    
        private string[] textField;
    
        /// <remarks/>
        [XmlAnyElement()]
        [XmlElement("DSAKeyValue", typeof(DSAKeyValueType))]
        [XmlElement("RSAKeyValue", typeof(RSAKeyValueType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType {
    
        private object[] itemsField;
    
        private ItemsChoiceType2[] itemsElementNameField;
    
        private string[] textField;
    
        private string idField;
    
        /// <remarks/>
        [XmlAnyElement()]
        [XmlElement("KeyName", typeof(string))]
        [XmlElement("KeyValue", typeof(KeyValueType))]
        [XmlElement("MgmtData", typeof(string))]
        [XmlElement("PGPData", typeof(PGPDataType))]
        [XmlElement("RetrievalMethod", typeof(RetrievalMethodType))]
        [XmlElement("SPKIData", typeof(SPKIDataType))]
        [XmlElement("X509Data", typeof(X509DataType))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
    
        /// <remarks/>
        [XmlEnum("##any:")]
        Item,
    
        /// <remarks/>
        KeyName,
    
        /// <remarks/>
        KeyValue,
    
        /// <remarks/>
        MgmtData,
    
        /// <remarks/>
        PGPData,
    
        /// <remarks/>
        RetrievalMethod,
    
        /// <remarks/>
        SPKIData,
    
        /// <remarks/>
        X509Data,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureValueType {
    
        private string idField;
    
        private byte[] valueField;
    
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlText(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType {
    
        private TransformType[] transformsField;
    
        private DigestMethodType digestMethodField;
    
        private DigestValueType digestValueField;
    
        private string idField;
    
        private string uRIField;
    
        private string typeField;
    
        /// <remarks/>
        [XmlArrayItem("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
    
        /// <remarks/>
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
    
        /// <remarks/>
        public DigestValueType DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethodType {
    
        private System.Xml.XmlNode[] anyField;
    
        private string algorithmField;
    
        /// <remarks/>
        [XmlText()]
        [XmlAnyElement()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestValueType {
    
        private byte[] valueField;
    
        /// <remarks/>
        [XmlText(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethodType {
    
        private string hMACOutputLengthField;
    
        private System.Xml.XmlNode[] anyField;
    
        private string algorithmField;
    
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string HMACOutputLength {
            get {
                return this.hMACOutputLengthField;
            }
            set {
                this.hMACOutputLengthField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        [XmlAnyElement()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethodType {
    
        private System.Xml.XmlNode[] anyField;
    
        private string algorithmField;
    
        /// <remarks/>
        [XmlText()]
        [XmlAnyElement()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType {
    
        private CanonicalizationMethodType canonicalizationMethodField;
    
        private SignatureMethodType signatureMethodField;
    
        private ReferenceType[] referenceField;
    
        private string idField;
    
        /// <remarks/>
        public CanonicalizationMethodType CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
    
        /// <remarks/>
        public SignatureMethodType SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Reference")]
        public ReferenceType[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureType {
    
        private SignedInfoType signedInfoField;
    
        private SignatureValueType signatureValueField;
    
        private KeyInfoType keyInfoField;
    
        private ObjectType[] objectField;
    
        private string idField;
    
        /// <remarks/>
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
    
        /// <remarks/>
        public SignatureValueType SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
    
        /// <remarks/>
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Object")]
        public ObjectType[] Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class InternationalStringType {
    
        private string langField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class ResponseBaseType {
    
        private Result resultField;
    
        private AnyType optionalOutputsField;
    
        private string requestIDField;
    
        private string profileField;
    
        /// <remarks/>
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    
        /// <remarks/>
        public AnyType OptionalOutputs {
            get {
                return this.optionalOutputsField;
            }
            set {
                this.optionalOutputsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class Result {
    
        private string resultMajorField;
    
        private string resultMinorField;
    
        private InternationalStringType resultMessageField;
    
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string ResultMajor {
            get {
                return this.resultMajorField;
            }
            set {
                this.resultMajorField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string ResultMinor {
            get {
                return this.resultMinorField;
            }
            set {
                this.resultMinorField = value;
            }
        }
    
        /// <remarks/>
        public InternationalStringType ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class AttachmentReferenceType {
    
        private DigestMethodType digestMethodField;
    
        private DigestValueType digestValueField;
    
        private string attRefURIField;
    
        private string mimeTypeField;
    
        /// <remarks/>
        [XmlElement(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public DigestValueType DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string AttRefURI {
            get {
                return this.attRefURIField;
            }
            set {
                this.attRefURIField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class InlineXMLType {
    
        private System.Xml.XmlElement anyField;
    
        private bool ignorePIsField;
    
        private bool ignoreCommentsField;
    
        public InlineXMLType() {
            this.ignorePIsField = true;
            this.ignoreCommentsField = true;
        }
    
        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(true)]
        public bool ignorePIs {
            get {
                return this.ignorePIsField;
            }
            set {
                this.ignorePIsField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(true)]
        public bool ignoreComments {
            get {
                return this.ignoreCommentsField;
            }
            set {
                this.ignoreCommentsField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(DocumentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public abstract partial class DocumentBaseType {
    
        private string idField;
    
        private string refURIField;
    
        private string refTypeField;
    
        private string schemaRefsField;
    
        /// <remarks/>
        [XmlAttribute(DataType="ID")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string RefURI {
            get {
                return this.refURIField;
            }
            set {
                this.refURIField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string RefType {
            get {
                return this.refTypeField;
            }
            set {
                this.refTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="IDREFS")]
        public string SchemaRefs {
            get {
                return this.schemaRefsField;
            }
            set {
                this.schemaRefsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class DocumentType : DocumentBaseType {
    
        private object itemField;
    
        /// <remarks/>
        [XmlElement("AttachmentReference", typeof(AttachmentReferenceType))]
        [XmlElement("Base64Data", typeof(Base64Data))]
        [XmlElement("Base64XML", typeof(byte[]), DataType="base64Binary")]
        [XmlElement("EscapedXML", typeof(string))]
        [XmlElement("InlineXML", typeof(InlineXMLType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class Base64Data {
    
        private string mimeTypeField;
    
        private byte[] valueField;
    
        /// <remarks/>
        [XmlAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlText(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class InputDocuments {
    
        private object[] itemsField;
    
        /// <remarks/>
        [XmlElement("Document", typeof(DocumentType))]
        [XmlElement("DocumentHash", typeof(DocumentHash))]
        [XmlElement("Other", typeof(AnyType))]
        [XmlElement("TransformedData", typeof(TransformedData))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class DocumentHash : DocumentBaseType {
    
        private TransformType[] transformsField;
    
        private DigestMethodType digestMethodField;
    
        private DigestValueType digestValueField;
    
        private string whichReferenceField;
    
        /// <remarks/>
        [XmlArray(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        [XmlArrayItem("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public DigestValueType DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="integer")]
        public string WhichReference {
            get {
                return this.whichReferenceField;
            }
            set {
                this.whichReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class TransformedData : DocumentBaseType {
    
        private TransformType[] transformsField;
    
        private Base64Data base64DataField;
    
        private string whichReferenceField;
    
        /// <remarks/>
        [XmlArray(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        [XmlArrayItem("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
    
        /// <remarks/>
        public Base64Data Base64Data {
            get {
                return this.base64DataField;
            }
            set {
                this.base64DataField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="integer")]
        public string WhichReference {
            get {
                return this.whichReferenceField;
            }
            set {
                this.whichReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class SignResponse : ResponseBaseType {
    
        private SignatureObject signatureObjectField;
    
        /// <remarks/>
        public SignatureObject SignatureObject {
            get {
                return this.signatureObjectField;
            }
            set {
                this.signatureObjectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class SignatureObject {
    
        private object itemField;
    
        private string schemaRefsField;
    
        /// <remarks/>
        [XmlElement("Signature", typeof(SignatureType), Namespace="http://www.w3.org/2000/09/xmldsig#")]
        [XmlElement("Base64Signature", typeof(Base64Signature))]
        [XmlElement("Other", typeof(AnyType))]
        [XmlElement("SignaturePtr", typeof(SignaturePtr))]
        [XmlElement("Timestamp", typeof(Timestamp))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute(DataType="IDREFS")]
        public string SchemaRefs {
            get {
                return this.schemaRefsField;
            }
            set {
                this.schemaRefsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class Base64Signature {
    
        private string typeField;
    
        private byte[] valueField;
    
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlText(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class SignaturePtr {
    
        private string whichDocumentField;
    
        private string xPathField;
    
        /// <remarks/>
        [XmlAttribute(DataType="IDREF")]
        public string WhichDocument {
            get {
                return this.whichDocumentField;
            }
            set {
                this.whichDocumentField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class Timestamp {
    
        private object itemField;
    
        /// <remarks/>
        [XmlElement("Signature", typeof(SignatureType), Namespace="http://www.w3.org/2000/09/xmldsig#")]
        [XmlElement("Other", typeof(AnyType))]
        [XmlElement("RFC3161TimeStampToken", typeof(byte[]), DataType="base64Binary")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oasis:names:tc:dss:1.0:core:schema")]
    public partial class VerifyRequest : RequestBaseType {
    
        private SignatureObject signatureObjectField;
    
        /// <remarks/>
        public SignatureObject SignatureObject {
            get {
                return this.signatureObjectField;
            }
            set {
                this.signatureObjectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void createTimeStampCompletedEventHandler(object sender, createTimeStampCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class createTimeStampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal createTimeStampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
        }
    
        /// <remarks/>
        public SignResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SignResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void verifyTimeStampCompletedEventHandler(object sender, verifyTimeStampCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class verifyTimeStampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal verifyTimeStampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
        }
    
        /// <remarks/>
        public ResponseBaseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseBaseType)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void renewTimeStampCompletedEventHandler(object sender, renewTimeStampCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class renewTimeStampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
        private object[] results;
    
        internal renewTimeStampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
            this.results = results;
        }
    
        /// <remarks/>
        public SignRequest SignRequest {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SignRequest)(this.results[0]));
            }
        }
    }
}