//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace IntegraAfirmaNet.Schemas
{

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://afirmaws/ws/validacion", IsNullable = false)]
    public partial class mensajeEntrada
    {

        private mensajeEntradaPeticion peticionField;

        private string versionMsgField;

        private mensajeEntradaParametros parametrosField;

        /// <comentarios/>
        public mensajeEntradaPeticion peticion
        {
            get
            {
                return this.peticionField;
            }
            set
            {
                this.peticionField = value;
            }
        }

        /// <comentarios/>
        public string versionMsg
        {
            get
            {
                return this.versionMsgField;
            }
            set
            {
                this.versionMsgField = value;
            }
        }

        /// <comentarios/>
        public mensajeEntradaParametros parametros
        {
            get
            {
                return this.parametrosField;
            }
            set
            {
                this.parametrosField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public enum mensajeEntradaPeticion
    {

        /// <comentarios/>
        ValidarCertificado,

        /// <comentarios/>
        ObtenerInfoCertificado,
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class mensajeEntradaParametros
    {

        private byte[] certificadoField;

        private string idAplicacionField;

        private string modoValidacionField;

        private bool obtenerInfoField;

        private bool obtenerInfoFieldSpecified;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }

        /// <comentarios/>
        public string idAplicacion
        {
            get
            {
                return this.idAplicacionField;
            }
            set
            {
                this.idAplicacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string modoValidacion
        {
            get
            {
                return this.modoValidacionField;
            }
            set
            {
                this.modoValidacionField = value;
            }
        }

        /// <comentarios/>
        public bool obtenerInfo
        {
            get
            {
                return this.obtenerInfoField;
            }
            set
            {
                this.obtenerInfoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obtenerInfoSpecified
        {
            get
            {
                return this.obtenerInfoFieldSpecified;
            }
            set
            {
                this.obtenerInfoFieldSpecified = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://afirmaws/ws/validacion")]
    public partial class ValidacionCadenaInfo
    {

        private string codigoResultadoField;

        private string descResultadoField;

        private ValidacionCadenaInfoErrorCertificado[] errorCertificadoField;

        /// <comentarios/>
        public string codigoResultado
        {
            get
            {
                return this.codigoResultadoField;
            }
            set
            {
                this.codigoResultadoField = value;
            }
        }

        /// <comentarios/>
        public string descResultado
        {
            get
            {
                return this.descResultadoField;
            }
            set
            {
                this.descResultadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("errorCertificado")]
        public ValidacionCadenaInfoErrorCertificado[] errorCertificado
        {
            get
            {
                return this.errorCertificadoField;
            }
            set
            {
                this.errorCertificadoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class ValidacionCadenaInfoErrorCertificado
    {

        private string idCertificadoField;

        private ValidacionSimpleInfo validacionSimpleField;

        private ValidacionEstadoInfo validacionEstadoField;

        /// <comentarios/>
        public string idCertificado
        {
            get
            {
                return this.idCertificadoField;
            }
            set
            {
                this.idCertificadoField = value;
            }
        }

        /// <comentarios/>
        public ValidacionSimpleInfo ValidacionSimple
        {
            get
            {
                return this.validacionSimpleField;
            }
            set
            {
                this.validacionSimpleField = value;
            }
        }

        /// <comentarios/>
        public ValidacionEstadoInfo ValidacionEstado
        {
            get
            {
                return this.validacionEstadoField;
            }
            set
            {
                this.validacionEstadoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://afirmaws/ws/validacion")]
    public partial class ValidacionSimpleInfo
    {

        private string codigoResultadoField;

        private string descResultadoField;

        private string excepcionField;

        /// <comentarios/>
        public string codigoResultado
        {
            get
            {
                return this.codigoResultadoField;
            }
            set
            {
                this.codigoResultadoField = value;
            }
        }

        /// <comentarios/>
        public string descResultado
        {
            get
            {
                return this.descResultadoField;
            }
            set
            {
                this.descResultadoField = value;
            }
        }

        /// <comentarios/>
        public string excepcion
        {
            get
            {
                return this.excepcionField;
            }
            set
            {
                this.excepcionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://afirmaws/ws/validacion")]
    public partial class ValidacionEstadoInfo
    {

        private string estadoField;

        private string descEstadoField;

        private ValidacionEstadoInfoInfoMetodoVerificacion[] infoMetodoVerificacionField;

        /// <comentarios/>
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        public string descEstado
        {
            get
            {
                return this.descEstadoField;
            }
            set
            {
                this.descEstadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("InfoMetodoVerificacion")]
        public ValidacionEstadoInfoInfoMetodoVerificacion[] InfoMetodoVerificacion
        {
            get
            {
                return this.infoMetodoVerificacionField;
            }
            set
            {
                this.infoMetodoVerificacionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class ValidacionEstadoInfoInfoMetodoVerificacion
    {

        private string estadoField;

        private string descEstadoField;

        private string fechaUltimaActualizacionField;

        private string fechaRevocacionField;

        private string motivoField;

        private ValidacionEstadoInfoInfoMetodoVerificacionMetodo metodoField;

        private string tokenOCSPField;

        private string excepcionField;

        /// <comentarios/>
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        public string descEstado
        {
            get
            {
                return this.descEstadoField;
            }
            set
            {
                this.descEstadoField = value;
            }
        }

        /// <comentarios/>
        public string fechaUltimaActualizacion
        {
            get
            {
                return this.fechaUltimaActualizacionField;
            }
            set
            {
                this.fechaUltimaActualizacionField = value;
            }
        }

        /// <comentarios/>
        public string fechaRevocacion
        {
            get
            {
                return this.fechaRevocacionField;
            }
            set
            {
                this.fechaRevocacionField = value;
            }
        }

        /// <comentarios/>
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }

        /// <comentarios/>
        public ValidacionEstadoInfoInfoMetodoVerificacionMetodo Metodo
        {
            get
            {
                return this.metodoField;
            }
            set
            {
                this.metodoField = value;
            }
        }

        /// <comentarios/>
        public string tokenOCSP
        {
            get
            {
                return this.tokenOCSPField;
            }
            set
            {
                this.tokenOCSPField = value;
            }
        }

        /// <comentarios/>
        public string excepcion
        {
            get
            {
                return this.excepcionField;
            }
            set
            {
                this.excepcionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class ValidacionEstadoInfoInfoMetodoVerificacionMetodo
    {

        private string urlServidorField;

        private string protocoloField;

        /// <comentarios/>
        public string urlServidor
        {
            get
            {
                return this.urlServidorField;
            }
            set
            {
                this.urlServidorField = value;
            }
        }

        /// <comentarios/>
        public string protocolo
        {
            get
            {
                return this.protocoloField;
            }
            set
            {
                this.protocoloField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://afirmaws/ws/validacion")]
    public partial class ResultadoValidacionInfo
    {

        private string resultadoField;

        private string descripcionField;

        private ValidacionSimpleInfo validacionSimpleField;

        private ValidacionEstadoInfo validacionEstadoField;

        private ValidacionCadenaInfo validacionCadenaField;

        /// <comentarios/>
        public string resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }

        /// <comentarios/>
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <comentarios/>
        public ValidacionSimpleInfo ValidacionSimple
        {
            get
            {
                return this.validacionSimpleField;
            }
            set
            {
                this.validacionSimpleField = value;
            }
        }

        /// <comentarios/>
        public ValidacionEstadoInfo ValidacionEstado
        {
            get
            {
                return this.validacionEstadoField;
            }
            set
            {
                this.validacionEstadoField = value;
            }
        }

        /// <comentarios/>
        public ValidacionCadenaInfo ValidacionCadena
        {
            get
            {
                return this.validacionCadenaField;
            }
            set
            {
                this.validacionCadenaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://afirmaws/ws/validacion", IsNullable = false)]
    public partial class mensajeSalida
    {

        private mensajeSalidaPeticion peticionField;

        private string versionMsgField;

        private mensajeSalidaRespuesta respuestaField;

        /// <comentarios/>
        public mensajeSalidaPeticion peticion
        {
            get
            {
                return this.peticionField;
            }
            set
            {
                this.peticionField = value;
            }
        }

        /// <comentarios/>
        public string versionMsg
        {
            get
            {
                return this.versionMsgField;
            }
            set
            {
                this.versionMsgField = value;
            }
        }

        /// <comentarios/>
        public mensajeSalidaRespuesta respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public enum mensajeSalidaPeticion
    {

        /// <comentarios/>
        ValidarCertificado,

        /// <comentarios/>
        ObtenerInfoCertificado,
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class mensajeSalidaRespuesta
    {

        private object itemField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Excepcion", typeof(mensajeSalidaRespuestaExcepcion))]
        [System.Xml.Serialization.XmlElementAttribute("ResultadoProcesamiento", typeof(mensajeSalidaRespuestaResultadoProcesamiento))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class mensajeSalidaRespuestaExcepcion
    {

        private string codigoErrorField;

        private string descripcionField;

        private string excepcionAsociadaField;

        /// <comentarios/>
        public string codigoError
        {
            get
            {
                return this.codigoErrorField;
            }
            set
            {
                this.codigoErrorField = value;
            }
        }

        /// <comentarios/>
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <comentarios/>
        public string excepcionAsociada
        {
            get
            {
                return this.excepcionAsociadaField;
            }
            set
            {
                this.excepcionAsociadaField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class mensajeSalidaRespuestaResultadoProcesamiento
    {

        private InfoCertificadoInfoCampo[] infoCertificadoField;

        private ResultadoValidacionInfo resultadoValidacionField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Campo", IsNullable = false)]
        public InfoCertificadoInfoCampo[] InfoCertificado
        {
            get
            {
                return this.infoCertificadoField;
            }
            set
            {
                this.infoCertificadoField = value;
            }
        }

        /// <comentarios/>
        public ResultadoValidacionInfo ResultadoValidacion
        {
            get
            {
                return this.resultadoValidacionField;
            }
            set
            {
                this.resultadoValidacionField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://afirmaws/ws/validacion")]
    public partial class InfoCertificadoInfoCampo
    {

        private string idCampoField;

        private string valorCampoField;

        /// <comentarios/>
        public string idCampo
        {
            get
            {
                return this.idCampoField;
            }
            set
            {
                this.idCampoField = value;
            }
        }

        /// <comentarios/>
        public string valorCampo
        {
            get
            {
                return this.valorCampoField;
            }
            set
            {
                this.valorCampoField = value;
            }
        }
    }
}